### PR TITLE
Ensure read after write consistency

### PR DESCRIPTION
**Pull request by Jose10go**
this is, at least in my head, a possible solution for #146 cc: @Lith @qhoirulanwar

### CODE REVIEW

**Comment by Lith** [comment]
Hi @Jose10go !

Thanks for your contribution ❤️ 

Does someone else have try your solution ? 
I've no time to test... I can deploy with latest Strapi release and hope this will working fine 🤣 

Can you check the "test" failed ? 

Otherwise, your purpose seems really great !
Thanks :)

**Comment by Jose10go** [comment]
The test are running fine, at least locally. The github workflow is failling in the lint step and is pointing to a bigger problem wich is that the stream/promises module I am using for the solution was not introduced until node 15, the workflow is runing in node 12 (wich is deprecated by the way), I think we may want to upgrade the node version the workflow is running on to node 16, but that should be your call @Lith. Here is the link to nodejs endof life that could be useful https://endoflife.date/nodejs . Also 
in the package.json engine filed of this package is specified node 16 so i think should be fine to run the workflow in node 16. https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/blob/master/package.json#L58
As a side note I am actively using this solution now and the read after write inconsistency is fixed.

**Comment by wrz199306** [comment]
"Test" failed because the node version is too low(node-version: '12.x').
Maybe the node version should be updated in the "workflows/test.yml".
I really need this PR. Thx~

**Comment by Jose10go** [comment]
@Lith i just updated the node version the test workflow runs on... it is up to you now 😉

**Review by Lith — APPROVED** [review]

**Pull request merged**
